import { useState, useCallback } from "react";
import { motion } from "framer-motion";
import CyberBackground from "./components/CyberBackground";
import Header from "./components/Header";
import PipelineVisualizer from "./components/PipelineVisualizer";
import ModulePanel from "./components/ModulePanel";
import VulnerabilityGrid from "./components/VulnerabilityGrid";
import LiveConsole from "./components/LiveConsole";
import ResourceGauges from "./components/ResourceGauges";
import { pipelineStages, modules } from "./data/mockData";
import type { PipelineStage } from "./data/mockData";

function App() {
  const [isRunning, setIsRunning] = useState(false);
  const [stages, setStages] = useState<PipelineStage[]>(pipelineStages);
  const [moduleStates, setModuleStates] = useState<Record<string, boolean>>(
    () => Object.fromEntries(modules.map((m) => [m.id, m.enabled]))
  );

  const handleToggle = useCallback((id: string) => {
    setModuleStates((prev) => ({ ...prev, [id]: !prev[id] }));
  }, []);

  const handleRunPipeline = useCallback(() => {
    if (isRunning) return;
    setIsRunning(true);

    setStages((prev) =>
      prev.map((s, i) => {
        if (i === 0)
          return { ...s, status: "running" as const, duration: null, latency: 0 };
        return { ...s, status: "idle" as const, duration: null, latency: 0 };
      })
    );

    const sequence = [
      { delay: 3000, si: 0, status: "success" as const, duration: 12400 },
      { delay: 3500, si: 1, status: "running" as const, duration: null },
      { delay: 8000, si: 1, status: "success" as const, duration: 8200 },
      { delay: 8500, si: 2, status: "running" as const, duration: null },
      { delay: 14000, si: 2, status: "success" as const, duration: 6100 },
      { delay: 14500, si: 3, status: "running" as const, duration: null },
      { delay: 18000, si: 3, status: "success" as const, duration: 3400 },
      { delay: 18500, si: 4, status: "running" as const, duration: null },
      { delay: 22000, si: 4, status: "success" as const, duration: 2100 },
      { delay: 23000, si: -1, status: "idle" as const, duration: null },
    ];

    const timers = sequence.map(({ delay, si, status, duration }) =>
      setTimeout(() => {
        if (si === -1) {
          setIsRunning(false);
          setStages(pipelineStages);
          return;
        }
        setStages((prev) =>
          prev.map((s, i) =>
            i === si
              ? {
                  ...s,
                  status,
                  duration,
                  latency:
                    status === "running"
                      ? Math.floor(Math.random() * 500 + 200)
                      : s.latency,
                }
              : s
          )
        );
      }, delay)
    );

    return () => timers.forEach(clearTimeout);
  }, [isRunning]);

  const handleExport = useCallback(() => {
    alert(
      "Report export initiated. HTML report will be generated by reporting/generator.py"
    );
  }, []);

  return (
    <div className="min-h-screen relative">
      <CyberBackground />

      <div className="relative z-10 max-w-[1600px] mx-auto p-3 sm:p-4 lg:p-5 space-y-3">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
        >
          <Header
            isRunning={isRunning}
            onRunPipeline={handleRunPipeline}
            onExport={handleExport}
          />
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3, delay: 0.05 }}
        >
          <PipelineVisualizer stages={stages} />
        </motion.div>

        <div className="grid grid-cols-1 xl:grid-cols-12 gap-3">
          <div className="xl:col-span-5 space-y-3">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.3, delay: 0.1 }}
            >
              <ModulePanel moduleStates={moduleStates} onToggle={handleToggle} />
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.3, delay: 0.15 }}
            >
              <VulnerabilityGrid />
            </motion.div>
          </div>

          <div className="xl:col-span-7 space-y-3">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.3, delay: 0.1 }}
            >
              <LiveConsole />
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.3, delay: 0.15 }}
            >
              <ResourceGauges />
            </motion.div>
          </div>
        </div>

        <div className="text-center py-4 text-[10px] text-text-muted font-mono tracking-wider">
          AEGIS v0.1.0 // AUTONOMOUS EXPLOITATION-GRADED INCIDENT-VERIFICATION
          SYSTEM
          <br />
          LAB MODE ACTIVE — ALL OPERATIONS SCOPE-GATED AND AUTHORIZED
        </div>
      </div>
    </div>
  );
}

export default App;
